spring:
  profiles:
    include: secret

  jackson:
    time-zone: Asia/Seoul

  modulith:
    events:
      jdbc-schema-initialization.enabled: true
      republish-outstanding-events-on-restart: true

sse:
  heartbeat-interval: 30 # 30초
  default-timeout: 1800 # 30분

mail:
  from:
    address: noreply@bob.com
    personal: Bookbridge